#!/bin/bash

echo "🔥 Configuración Completa de Firebase"
echo "====================================="

echo ""
echo "✅ Credenciales configuradas en environment.ts"
echo "   - Project ID: aki-app-2d2d8"
echo "   - API Key: Configurada"
echo "   - Auth Domain: aki-app-2d2d8.firebaseapp.com"

echo ""
echo "📋 Pasos restantes en Firebase Console:"
echo ""
echo "1. 🔐 Habilita Authentication:"
echo "   - Ve a: https://console.firebase.google.com/project/aki-app-2d2d8/authentication"
echo "   - Click en 'Sign-in method'"
echo "   - Habilita 'Google'"
echo "   - Configura dominios autorizados:"
echo "     ✅ localhost (para desarrollo)"
echo "     ✅ 127.0.0.1 (para desarrollo)"
echo "     ✅ tu-dominio.com (para producción)"

echo ""
echo "2. 📱 Configura la app web:"
echo "   - Ve a: https://console.firebase.google.com/project/aki-app-2d2d8/settings/general"
echo "   - En 'Your apps' agrega una app web si no existe"
echo "   - Asegúrate que el dominio esté autorizado"

echo ""
echo "💰 COSTOS DE FIREBASE:"
echo "======================="
echo ""
echo "🆓 GRATIS (Plan Spark):"
echo "   ✅ Authentication: Ilimitado"
echo "   ✅ Firestore: 1GB almacenamiento"
echo "   ✅ Storage: 5GB"
echo "   ✅ Hosting: 10GB transferencia"
echo "   ✅ Funciones: 125K invocaciones/mes"
echo ""
echo "💳 PAGO (Plan Blaze - Pay as you go):"
echo "   - Solo pagas por lo que uses"
echo "   - Authentication: GRATIS"
echo "   - Firestore: $0.18 por 100K lecturas"
echo "   - Storage: $0.026 por GB"
echo ""
echo "🎯 PARA TU APP:"
echo "   - Authentication con Google: GRATIS"
echo "   - Login/Registro: GRATIS"
echo "   - Usuarios ilimitados: GRATIS"
echo ""
echo "📊 Límites gratuitos (más que suficientes):"
echo "   - 50K usuarios autenticados/mes"
echo "   - 1GB base de datos"
echo "   - 10GB hosting"

echo ""
echo "🚀 Estado actual:"
echo "✅ Credenciales configuradas"
echo "✅ Servidor funcionando"
echo "✅ Login disponible en /tabs/tab3"
echo "⏳ Solo falta habilitar Google Auth en Firebase Console"

echo ""
echo "📱 Para probar:"
echo "   - http://localhost:8101/tabs/tab3"
echo "   - Una vez configurado Google Auth, el login funcionará"

echo ""
echo "🔗 Enlaces directos:"
echo "   - Console: https://console.firebase.google.com/project/aki-app-2d2d8"
echo "   - Auth: https://console.firebase.google.com/project/aki-app-2d2d8/authentication"
echo "   - Settings: https://console.firebase.google.com/project/aki-app-2d2d8/settings/general"
