#!/bin/bash

echo "🔥 Guía para Configurar Firebase Real"
echo "======================================"

echo ""
echo "📋 Pasos para configurar Firebase:"
echo ""
echo "1. 🌐 Ve a https://console.firebase.google.com/"
echo ""
echo "2. 📝 Crea un nuevo proyecto:"
echo "   - Nombre: 'AKI Conecta Personal'"
echo "   - Habilitar Google Analytics (opcional)"
echo ""
echo "3. 🔐 Habilita Authentication:"
echo "   - Ve a 'Authentication' > 'Sign-in method'"
echo "   - Habilita 'Google'"
echo "   - Configura el dominio autorizado:"
echo "     - localhost (para desarrollo)"
echo "     - tu-dominio.com (para producción)"
echo ""
echo "4. 📱 Configura la aplicación web:"
echo "   - Ve a 'Project settings' (ícono de engranaje)"
echo "   - Agrega una app web"
echo "   - Copia la configuración que aparece"
echo ""
echo "5. 📄 Reemplaza en environment.ts:"
echo "   - apiKey: 'tu-api-key-real'"
echo "   - authDomain: 'tu-proyecto.firebaseapp.com'"
echo "   - projectId: 'tu-proyecto-id'"
echo "   - storageBucket: 'tu-proyecto.appspot.com'"
echo "   - messagingSenderId: 'tu-sender-id'"
echo "   - appId: 'tu-app-id'"
echo ""

echo "🔧 Configuración actual (temporal):"
echo "   - Firebase está deshabilitado temporalmente"
echo "   - Login funciona en modo demo"
echo "   - Sin errores de API key"

echo ""
echo "📱 Para probar ahora:"
echo "   - http://localhost:8101/tabs/tab3"
echo "   - El login funcionará sin Firebase"

echo ""
echo "🚀 Una vez configurado Firebase:"
echo "   - Actualiza environment.ts con las credenciales reales"
echo "   - El login con Google funcionará completamente"

echo ""
echo "❓ ¿Necesitas ayuda con algún paso?"
echo "   - Revisa la documentación de Firebase"
echo "   - https://firebase.google.com/docs/auth/web/google-signin"
